# https://learn.microsoft.com/azure/devops/pipelines/ecosystems/android
pool:
  vmImage: 'macOS-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: $(system.defaultWorkingDirectory)/AndroidApps/MyApp
    gradleWrapperFile: $(system.defaultWorkingDirectory)/AndroidApps/MyApp/gradlew
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'